name: test

on:
  push:
    branches-ignore:
      - gh-pages
      - main
  pull_request:
    branches-ignore:
      - gh-pages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout master
      uses: actions/checkout@v2
      with:
        submodules: true  # Fetch Hugo themes (true OR recursive)
        fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true
    - name: Test
      run: hugo -v --gc
    - name: Check HTML
      uses: chabad360/htmlproofer@master
      with:
        directory: "./public"
        arguments: --check-html --allow-hash-href --empty-alt-ignore --disable-external
